#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

echo "==> Cleaning repository"
cargo clean

echo "==> Running bootstrap"
script/bootstrap

# TODO schema change for when we introduce the db